server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/course
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      dll-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

app:
  security:
    jwt:
      access-expires-at: 900_000 #ms -15ph
      refresh-expires-at: 2_592_000_000 #30day
      prefix: "Bearer "
      auth-header: "Authorization"
      access-secret: access
      refresh-secret: refresh
